version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5430:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_ROOT_PASSWORD: secret
        POSTGRES_DATABASE: stage
        POSTGRES_USER: example
        POSTGRES_PASSWORD: secret2












